[model]
name = "Blog"
label = "Blog Post"

[fields.sort_key]
label = "Sort order"
type = "sort_key"

[fields.title]
label = "Title"
type = "string"

[fields.summary]
label = "Title"
type = "markdown"

[fields.body]
label = "Body"
type = "markdown"