[model]
name = "Page"
label = "My Website!"

[fields.title]
label = "Title"
type = "string"

[fields.body]
label = "Body"
type = "markdown"

[fields.body_class]
label = "Body Class"
type = "string"
width = "1/4"